# Generated by Django 5.1.15 on 2026-06-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_habilitar_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='estado_sii',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('emitida', 'Emitida'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='boleta',
            name='pdf_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='boleta',
            name='sii_codigo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
